In [10]:
import tensorflow as tf
import numpy as np

In [18]:
rand_array = np.random.randint(1,100,size=(10,2))

In [24]:
tensor = tf.constant(rand_array)
t = tf.data.Dataset.from_tensors(tensor).batch(3)
[x for x in t]

[<tf.Tensor: shape=(1, 10, 2), dtype=int64, numpy=
 array([[[36, 40],
         [57, 14],
         [19, 70],
         [44, 61],
         [63, 71],
         [17, 40],
         [32, 10],
         [97, 96],
         [60, 35],
         [31, 76]]])>]

In [26]:
tensor = tf.constant(rand_array)
t = tf.data.Dataset.from_tensor_slices(tensor).shuffle(1000).batch(4)
[x for x in t]

[<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
 array([[17, 40],
        [60, 35],
        [63, 71],
        [36, 40]])>,
 <tf.Tensor: shape=(4, 2), dtype=int64, numpy=
 array([[31, 76],
        [44, 61],
        [97, 96],
        [32, 10]])>,
 <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[57, 14],
        [19, 70]])>]